export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const TOGGLE_ITEM_COMPLETION = 'TOGGLE_ITEM_COMPLETION';
export const START_EDIT_ITEM = 'START_EDIT_ITEM';
export const FINISH_EDIT_ITEM = 'FINISH_EDIT_ITEM';